import { ArrowUpRight, Eye, Gamepad2, Orbit, Target } from "lucide-react";
import { challenges, contentWorlds, loopFamilies } from "@/data/challenge-engine";
import { ProceduralVisual } from "./ProceduralVisual";
import { Reveal, SectionHeader, StatusBadge, TechnicalLabel } from "./Primitives";

const worldIcons = { game: Gamepad2, loop: Orbit, target: Target };

export function ContentWorlds() {
  return <section className="section" id="content"><div className="section-inner"><SectionHeader label="03 / CONTENT SYSTEMS" title={<>THREE WAYS TO<br /><span>GENERATE MOTION.</span></>} description="Different content. Shared production philosophy." /><div className="world-grid">{contentWorlds.map((world, index) => { const Icon = worldIcons[world.icon]; return <Reveal key={world.title} delay={index * .08} className="world-card"><div className="world-index">{world.index}</div><Icon /><TechnicalLabel>{world.tag}</TechnicalLabel><h3>{world.title}</h3><p>{world.text}</p><div className="chip-list">{world.details.map((detail) => <span key={detail}>{detail}</span>)}</div></Reveal>})}</div></div></section>;
}

export function Challenges() {
  return <section className="section challenges-section"><div className="section-inner"><SectionHeader label="04 / CHALLENGE CATALOG" title={<>NINE CHALLENGES.<br /><span>ONE ENGINE.</span></>} description="Recovered mechanics normalized through a shared production architecture." /><div className="challenge-grid">{challenges.map((challenge, index) => <Reveal key={challenge.id} delay={(index % 3) * .06} className="challenge-card"><div className="challenge-top"><TechnicalLabel>{challenge.id}</TechnicalLabel><ArrowUpRight size={17} /></div><div className={`challenge-glyph glyph-${(index % 5) + 1}`}><span /><i /><b>{String(index + 1).padStart(2, "0")}</b></div><h3>{challenge.name}</h3><dl><div><dt>MECHANIC</dt><dd>{challenge.name}</dd></div><div><dt>ASSET FAMILY</dt><dd className={challenge.assetFamily === "UNKNOWN" ? "unknown" : ""}>{challenge.assetFamily}</dd></div><div><dt>VERSION</dt><dd className={challenge.version === "UNKNOWN" ? "unknown" : ""}>{challenge.version}</dd></div><div><dt>STATUS</dt><dd><StatusBadge tone={challenge.status}>{challenge.status === "closed" ? "EVIDENCE" : "UNKNOWN"}</StatusBadge></dd></div></dl></Reveal>)}</div></div></section>;
}

export function AssetFamilies() {
  return <section className="section asset-section"><div className="section-inner asset-layout"><div><SectionHeader label="05 / DECLARATIVE ASSETS" title={<>ASSETS ARE DATA.<br /><span>NOT DECORATION.</span></>} description="Reusable assets are represented declaratively so visual identity can evolve without rewriting the mechanics." /><p className="section-copy">Identity, family, role and provenance remain separate. <strong>UNKNOWN is not a bug. It is an evidence state.</strong></p></div><div className="family-map"><div className="family-node family-known"><TechnicalLabel>FAMILY</TechnicalLabel><b>fam_001</b><span>CHALLENGE_001</span><span>CHALLENGE_003</span></div><div className="family-node family-known"><TechnicalLabel>FAMILY</TechnicalLabel><b>fam_garage_01</b><span>CHALLENGE_002</span><span>CHALLENGE_004</span></div><div className="unknown-stack">{Array.from({ length: 5 }).map((_, i) => <div key={i}><Eye size={14} /><span>FAMILY UNKNOWN</span><small>EVIDENCE STATE</small></div>)}</div></div></div><div className="reuse-strip"><div><TechnicalLabel>CROSS-FAMILY REUSE</TechnicalLabel><strong>1</strong></div><h3>REUSE WITHOUT COLLAPSE.</h3><p>An asset can legitimately be reused across families. Shared assets do not automatically become the same family. Identity is preserved. Reuse is declared. Evidence remains traceable.</p></div></section>;
}

export function VisualSystems() {
  const drills = ["TRACKING", "SACCADE", "PURSUIT", "PERIPHERAL"];
  return <><section className="section loops-section"><div className="section-inner"><SectionHeader label="06 / VISUAL LOOPS" title="PROCEDURAL WORLDS." description="Continuous systems built from mathematical motion, rhythm and visual grammar." /><div className="loop-grid">{loopFamilies.map((family, index) => <Reveal key={family.name} className={`loop-card loop-card-${index + 1}`}><ProceduralVisual type={family.type} compact /><div><TechnicalLabel>LOOP FAMILY / {String(index + 1).padStart(2, "0")}</TechnicalLabel><h3>{family.name}</h3><p>{family.text}</p></div></Reveal>)}</div></div></section><section className="section drills-section"><div className="section-inner drill-layout"><div><SectionHeader label="07 / VISUAL DRILLS" title={<>MOTION WITH<br /><span>INTENT.</span></>} description="Visual Drills turn motion into attention mechanics. The point is controlled perceptual behavior—not simply movement." /><div className="drill-indicators">{["TIMING", "TRAJECTORY", "FIXATION", "SACCADE", "PERIPHERAL FIELD"].map(x => <span key={x}>{x}</span>)}</div></div><div className="drill-orbit"><div className="orbit-center"><Target /><small>ATTENTION<br />MECHANICS</small></div>{drills.map((name, i) => <div key={name} className={`orbit-item orbit-item-${i + 1}`}><span>{name}</span></div>)}</div></div></section></>;
}