import { useState } from "react";
import { Check, ChevronDown, Hash, RefreshCcw, ShieldCheck, Volume2 } from "lucide-react";
import { principles, roadmap } from "@/data/challenge-engine";
import { CodePanel, Reveal, SectionHeader, StatusBadge, TechnicalLabel } from "./Primitives";
import { ProceduralVisual } from "./ProceduralVisual";

const seeds = [12345, 314159, 54321, 7770001, 998877];

export function Determinism({ seed, onSeedChange }: { seed: number; onSeedChange: (seed: number) => void }) {
  function regenerate() { const i = seeds.indexOf(seed); onSeedChange(seeds[(i + 1) % seeds.length] ?? 12345); }
  return <section className="section determinism-section" id="determinism"><div className="section-inner"><SectionHeader label="08 / DETERMINISM" title={<>SAME SEED.<br /><span>SAME TRUTH.</span></>} description="Determinism is not a visual trick. It is the foundation that makes production reproducible, inspectable and testable." /><div className="determinism-layout"><CodePanel label="DEMO / VISUALIZATION" className="seed-panel"><div className="seed-control"><label htmlFor="seed-value"><Hash size={15} /> SEED</label><input id="seed-value" value={seed} readOnly /><button type="button" onClick={regenerate}><RefreshCcw size={15} /> REGENERATE</button></div><div className="run-comparison"><div><TechnicalLabel>RUN A</TechnicalLabel><Check /><span>STRUCTURAL OUTPUT</span></div><div><TechnicalLabel>RUN B</TechnicalLabel><Check /><span>STRUCTURAL OUTPUT</span></div><strong>=</strong></div><div className="result-identical"><ShieldCheck /><span>RESULT</span><b>IDENTICAL STRUCTURAL OUTPUT</b></div></CodePanel><div className="rng-separation"><TechnicalLabel>SEPARATED RESPONSIBILITY</TechnicalLabel><div><span>STRUCTURAL RNG</span><b>≠</b><span>MUSIC RNG <small>TARGET ARCHITECTURE</small></span><b>≠</b><span>PRESENTATION STATE</span></div><p>Randomness must be separated by responsibility.</p></div></div></div></section>;
}

export function ProvenanceAudio() {
  const metadata = [["CHALLENGE_ID", "CHALLENGE_001"], ["MECHANIC", "KEY"], ["VERSION", "1.0"], ["SEED", "12345"], ["ASSET_FAMILY", "fam_001"], ["PROFILE", "REVIEW_720"], ["SOURCE_REV", "C11-D"], ["STATUS", "DETERMINISTIC"]];
  return <><section className="section provenance-section"><div className="section-inner provenance-layout"><div><SectionHeader label="09 / PROVENANCE" title={<>EVERY ARTIFACT<br /><span>LEAVES A TRACE.</span></>} description="The goal is not merely to generate a video. The goal is to know how that video was generated." /><div className="trace-line"><i /><span>SIMULATION</span><i /><span>ARTIFACT</span><i /><span>LINEAGE</span></div></div><CodePanel label="PROVENANCE / ARTIFACT METADATA"><dl className="metadata-list">{metadata.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></CodePanel></div></section><section className="section audio-section"><div className="audio-visual"><ProceduralVisual type="waves" /></div><div className="section-inner audio-content"><SectionHeader label="10 / AUDIO SYSTEM" title={<>SOUND SHOULD BELONG<br /><span>TO THE SYSTEM.</span></>} description="Music is treated as a production layer, not as an isolated soundtrack file." /><div className="audio-controls">{["TIMBRE", "HARMONY", "RHYTHM", "MOTIF", "TEXTURE", "SPATIAL"].map((x, i) => <div key={x}><Volume2 size={14}/><span>{x}</span><i style={{ width: `${40 + i * 8}%` }} /></div>)}</div><div className="style-profile"><TechnicalLabel>PLANNED STYLE PROFILE</TechnicalLabel><strong>CHALLENGE</strong><span>8-BIT / CHIPTUNE</span><StatusBadge tone="next">PLANNED</StatusBadge></div><p className="audio-note">The future Challenge sound identity is 8-bit/chiptune. The generation process itself should remain shared. <b>Style changes. Pipeline stays.</b></p><small>Visual Loops and Visual Drills keep their existing behavior. Challenge gets a style profile, not a duplicated music engine.</small></div></section></>;
}

export function EvolutionRoadmap() {
  return <><section className="section evolution-section"><div className="section-inner"><SectionHeader label="11 / CONVERGENCE" title={<>FROM VISUAL PROTOTYPES<br /><span>TO PRODUCTION SYSTEM.</span></>} /><div className="evolution-track">{[["C11-A / C11-B", "CHALLENGE ORIGINS", "Recovered challenge mechanics and historical content."], ["C11-C", "VISUAL PRODUCTION MATURITY", "Mature visual loops, drills, social presentation and production workflows."], ["C11-D", "NORMALIZATION", "Bring the lessons together without changing gameplay truth."], ["TARGET", "UNIFIED PRODUCTION PIPELINE", "A stronger, declarative, reproducible Challenge production architecture."]].map((item, i) => <Reveal key={item[0]} delay={i*.08} className="evolution-node"><span>{String(i + 1).padStart(2,"0")}</span><TechnicalLabel>{item[0]}</TechnicalLabel><h3>{item[1]}</h3><p>{item[2]}</p></Reveal>)}</div></div></section><section className="section roadmap-section" id="roadmap"><div className="section-inner"><SectionHeader label="12 / C11-D ROADMAP" title={<>THE ROAD TO<br /><span>PRODUCTION.</span></>} description="Production robustness comes first. New mechanics come last." /><div className="roadmap-list">{roadmap.map((item) => <div key={item.id} className="roadmap-item"><strong>{item.id}</strong><div><h3>{item.title}</h3><p>{item.detail}</p></div><StatusBadge tone={item.tone}>{item.status}</StatusBadge><ChevronDown size={16} /></div>)}</div></div></section></>;
}

export function PrinciplesStatus() {
  const [fingerprints, setFingerprints] = useState(false);
  return <><section className="section principles-section"><div className="section-inner"><SectionHeader label="13 / ENGINEERING PRINCIPLES" title="BUILT AROUND CONSTRAINTS." /><div className="principle-grid">{principles.map(([id, title, text]) => <Reveal key={id} className="principle"><span>{id}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section><section className="section status-section" id="status"><div className="section-inner status-layout"><div className="reference-build"><TechnicalLabel>REFERENCE BUILD</TechnicalLabel><div className="build-version"><strong>C11-C</strong><b>2.19.12</b><StatusBadge tone="closed">FROZEN</StatusBadge></div><p>IMMUTABLE REFERENCE BASELINE</p><button type="button" onClick={() => setFingerprints(!fingerprints)}>VIEW BUILD FINGERPRINTS <ChevronDown size={15} /></button>{fingerprints && <div className="fingerprints"><span>ZIP SHA-256</span><code>D85425CF18C5211C8497574F4FC66202D613EACC0EC14CD4E2FEF0B24F634A32</code><span>TREE SHA-256</span><code>2D39B7B923B42CDC6647A4D25493B75023CDD19CEE18214BBDE1FDD295B8F256</code></div>}</div><CodePanel label="PROJECT STATUS / SYSTEM CURRENT STATE"><dl className="system-state">{[["ENGINE","CHALLENGE ENGINE"],["BRANCH","C11-D"],["C11-C","FROZEN / 2.19.12"],["D0","CLOSED / PASS"],["D1","CLOSED"],["D2","CLOSED"],["D3","NEXT"],["RUNTIME","DETERMINISTIC"],["PRESENTATION","DECLARATIVE"],["ASSETS","EVIDENCE-BACKED"],["PROVENANCE","ENABLED BY DESIGN"]].map(([k,v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></CodePanel></div></section></>;
}